pnpMode: "loose"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js

packageExtensions:
  "debug@*":
    peerDependenciesMeta:
      "supports-color": 
        optional: true
  "@webpack-cli/package-utils@*":
    dependencies: 
      "cross-spawn":  '*'
  
initScope: hexdev
