initScope: hexdev

packageExtensions:
  "@webpack-cli/package-utils@*":
    dependencies:
      cross-spawn: "*"
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.34.js
