name: 'Setup cross compiler toolchain'
description: 'Setup cross compiler toolchain.'
author: 'Czwl Cd'
runs:
  using: 'node12'
  main: 'dist/index.cjs'

inputs:
  toolchains:
    description: 'Comma seperated values of required toolchains'
    required: false
    default: 'gcc-arm'